import type {NextPage} from 'next'
import styles from '../styles/Home.module.css'
import Head from "next/head";
import FullPage from "components/FullPage";
import Canvas from "../components/Canvs";

const Home: NextPage = () => {
    return (
        <div>
            {/*<Head>*/}
            {/*    <title>AKV</title>*/}
            {/*    <meta name="description" content="Generated by create next app" />*/}
            {/*    <link rel="icon" href="/favicon.ico" />*/}
            {/*</Head>*/}
            <FullPage/>
            {process.browser ? <Canvas/> : null}
        </div>
    )
}

export default Home
