import type {NextPage} from 'next'
import styles from '../styles/Home.module.css'
import Head from "next/head";
import Viewer from "../components/Viewer";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>AKV</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Main Page</h1>
                <Viewer/>
            </main>
        </div>
    )
}

export default Home
